package com.systop.pss.service;

import com.systop.pss.model.UserInfo;
import com.systop.pss.service.dto.UserDto;

import java.util.List;

public interface UserInfoServcie {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    int deleteByPrimaryKey(String uuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    UserInfo selectByPrimaryKey(String uuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    int updateByPrimaryKey(UserInfo record);

    /**
     * 查询所有用户信息
     */
    List<UserInfo> selectUserList();

    /**
     * 用户登录鉴证
     * @param userDto
     */
    UserInfo login(UserDto userDto);

    /**
     * 根据手机查询用户信息
     * @return
     */
    UserInfo selectUserByTelPhone(String telPhone);
}
