package com.systop.pss.service.dto;

import java.util.Date;

public class UserDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.uu_id
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private String uuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_age
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private Integer userAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.pwd
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.tel_phone
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private String telPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.department
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.work_age
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private Integer workAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.admin_flag
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private String adminFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.entry_time
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private Date entryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.dimission_flag
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private String dimissionFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.uu_id
     *
     * @return the value of user_info.uu_id
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public String getUuId() {
        return uuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.uu_id
     *
     * @param uuId the value for user_info.uu_id
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setUuId(String uuId) {
        this.uuId = uuId == null ? null : uuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_age
     *
     * @return the value of user_info.user_age
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_age
     *
     * @param userAge the value for user_info.user_age
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.tel_phone
     *
     * @return the value of user_info.tel_phone
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.tel_phone
     *
     * @param telPhone the value for user_info.tel_phone
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setTelPhone(String telPhone) {
        this.telPhone = telPhone == null ? null : telPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.department
     *
     * @return the value of user_info.department
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.department
     *
     * @param department the value for user_info.department
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.work_age
     *
     * @return the value of user_info.work_age
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public Integer getWorkAge() {
        return workAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.work_age
     *
     * @param workAge the value for user_info.work_age
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setWorkAge(Integer workAge) {
        this.workAge = workAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.admin_flag
     *
     * @return the value of user_info.admin_flag
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public String getAdminFlag() {
        return adminFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.admin_flag
     *
     * @param adminFlag the value for user_info.admin_flag
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setAdminFlag(String adminFlag) {
        this.adminFlag = adminFlag == null ? null : adminFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.entry_time
     *
     * @return the value of user_info.entry_time
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.entry_time
     *
     * @param entryTime the value for user_info.entry_time
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.dimission_flag
     *
     * @return the value of user_info.dimission_flag
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public String getDimissionFlag() {
        return dimissionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.dimission_flag
     *
     * @param dimissionFlag the value for user_info.dimission_flag
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setDimissionFlag(String dimissionFlag) {
        this.dimissionFlag = dimissionFlag == null ? null : dimissionFlag.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.pwd
     *
     * @return the value of user_password.pwd
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.pwd
     *
     * @param pwd the value for user_password.pwd
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

}
