package com.systop.pss.database.model;

public class UserPassword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.pwd_id
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private Integer pwdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.uu_id
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private String uuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.pwd
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    private String pwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.pwd_id
     *
     * @return the value of user_password.pwd_id
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public Integer getPwdId() {
        return pwdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.pwd_id
     *
     * @param pwdId the value for user_password.pwd_id
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setPwdId(Integer pwdId) {
        this.pwdId = pwdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.uu_id
     *
     * @return the value of user_password.uu_id
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public String getUuId() {
        return uuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.uu_id
     *
     * @param uuId the value for user_password.uu_id
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setUuId(String uuId) {
        this.uuId = uuId == null ? null : uuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_password.pwd
     *
     * @return the value of user_password.pwd
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_password.pwd
     *
     * @param pwd the value for user_password.pwd
     *
     * @mbggenerated Thu Nov 28 20:54:20 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }
}